name: Deploy FastAPI to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: SSH into EC2 & Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ubuntu
        key: ${{ secrets.AWS_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/fastapi-book-project
          git pull origin main
          docker stop fastapi || true
          docker rm fastapi || true
          docker build -t fastapi-app .
          docker run -d -p 8080:8000 --name fastapi fastapi-app
          sudo systemctl restart nginx
