name: Deploy FastAPI to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: SSH into EC2 & Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ubuntu
        key: ${{ secrets.AWS_PRIVATE_KEY }}
        script: |
          d /home/ubuntu/
            git clone <your-github-repo>
            cd fastapi-book-project1/
            git fetch origin main
            git reset --hard origin/main
            docker-compose up -d --build
