name: Test Secrets

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display Secrets
        run: |
          echo "Heroku API Key: ${{ secrets.HEROKU_API_KEY }}"
          echo "Heroku App Name: ${{ secrets.HEROKU_APP_NAME }}"
